
-- +goose Up
-- SQL in section 'Up' is executed when this migration is applied
INSERT INTO websites (id, name, url, company_name) VALUES (1, 'ZUU online', 'https://zuuonline.com/', '株式会社ZUU');
INSERT INTO websites (id, name, url, company_name) VALUES (2, 'ferret（フェレット）', 'https://ferret-plus.com/', '株式会社ベーシック');
INSERT INTO websites (id, name, url, company_name) VALUES (3, 'バズ部', 'https://bazubu.com/', '株式会社ルーシー');
INSERT INTO websites (id, name, url, company_name) VALUES (4, 'FASHION PRESS（ファッションプレス）', 'https://www.fashion-press.net/', '株式会社カーリン');
INSERT INTO websites (id, name, url, company_name) VALUES (5, 'HYPEBEAST（ハイプビースト）', 'https://hypebeast.com/jp', 'Hypebeast Ltd.');
INSERT INTO websites (id, name, url, company_name) VALUES (6, '北欧、暮らしの道具店', 'https://hokuohkurashi.com/', '株式会社クラシコム');
INSERT INTO websites (id, name, url, company_name) VALUES (7, 'MONOCO（モノコ）', 'https://monoco.jp/', '株式会社MONOCO');
INSERT INTO websites (id, name, url, company_name) VALUES (8, 'AXIS（アクシス）', 'https://www.axismag.jp/', '株式会社アクシス');
INSERT INTO websites (id, name, url, company_name) VALUES (9, 'VICTORY（ビクトリー）', 'https://victorysportsnews.com/', '株式会社VICTORY');
INSERT INTO websites (id, name, url, company_name) VALUES (10, 'REALSPORTS（リアルスポーツ）', 'https://real-sports.jp/', '株式会社 REAL SPORTS');
INSERT INTO websites (id, name, url, company_name) VALUES (11, 'BASKETBALLKING（バスケットボールキング）', 'https://basketballking.jp/', '株式会社フロムワン');
INSERT INTO websites (id, name, url, company_name) VALUES (12, 'cinra（シンラ）', 'https://www.cinra.net/', '株式会社cinra');
INSERT INTO websites (id, name, url, company_name) VALUES (13, 'GQ', 'https://www.gqjapan.jp/', '合同会社コンデナスト・ジャパン');
INSERT INTO websites (id, name, url, company_name) VALUES (14, 'TASCLAP（タスクラップ）', 'https://mens.tasclap.jp/', '株式会社カカクコム');
INSERT INTO websites (id, name, url, company_name) VALUES (15, 'Smartlog（スマートログ）', 'https://smartlog.jp/', '株式会社Smartlog');
INSERT INTO websites (id, name, url, company_name) VALUES (16, 'modelpress（モデルプレス）', 'https://mdpr.jp/', '株式会社ネットネイティブ');
INSERT INTO websites (id, name, url, company_name) VALUES (17, 'マイナビウーマン', 'https://woman.mynavi.jp/', '株式会社マイナビ');
INSERT INTO websites (id, name, url, company_name) VALUES (18, '美的.com', 'https://www.biteki.com/', '株式会社小学館');
INSERT INTO websites (id, name, url, company_name) VALUES (19, 'HugKum（はぐくむ）', 'https://hugkum.sho.jp/', '株式会社小学館');
INSERT INTO websites (id, name, url, company_name) VALUES (20, 'kodomoe（コドモエ）', 'https://kodomoe.net/', '株式会社白泉社');
INSERT INTO websites (id, name, url, company_name) VALUES (21, 'KIDSNA（キズナ）', 'https://kidsna.com/magazine', '株式会社ネクストビート');
INSERT INTO websites (id, name, url, company_name) VALUES (22, 'ことりっぷWEB', 'https://co-trip.jp/', '株式会社昭文社ホールディングス');
INSERT INTO websites (id, name, url, company_name) VALUES (23, 'たびらい沖縄', 'https://www.tabirai.net/s/sightseeing/okinawa/', '株式会社パム');
INSERT INTO websites (id, name, url, company_name) VALUES (24, 'tsunagu Japan', 'https://www.tsunagujapan.com/', '株式会社D2CX');
INSERT INTO websites (id, name, url, company_name) VALUES (25, 'FiNc U（フィンクユー）', 'https://u.finc.com', '株式会社 FiNC Technologies');
INSERT INTO websites (id, name, url, company_name) VALUES (26, 'MELOS（メロス）', 'https://melos.media/', '株式会社APPY');
INSERT INTO websites (id, name, url, company_name) VALUES (27, 'Ccury（キュリー）', 'https://cury.jp/media/', '株式会社UOCC');
INSERT INTO websites (id, name, url, company_name) VALUES (28, 'Career Supli（キャリアサプリ）', 'https://careersupli.jp/', 'アデコ株式会社');
INSERT INTO websites (id, name, url, company_name) VALUES (29, 'CarMe（カーミー）', 'https://car-me.jp/', '株式会社ファブリカコミュニケーションズ');
INSERT INTO websites (id, name, url, company_name) VALUES (30, 'TAKIBI（タキビ）', 'https://www.takibi-reservation.style/media/', '株式会社フォーイット');
INSERT INTO websites (id, name, url, company_name) VALUES (31, 'いぬのきもち', 'https://dog.benesse.ne.jp/', '株式会社ベネッセコーポレーション');
INSERT INTO websites (id, name, url, company_name) VALUES (32, 'BUSINESS INSIDER JAPAN', 'https://www.businessinsider.jp/', '株式会社メディアジーン');
INSERT INTO websites (id, name, url, company_name) VALUES (33, '日経電子版', 'https://www.nikkei.com/', '株式会社日本経済新聞社');
INSERT INTO websites (id, name, url, company_name) VALUES (34, 'Newspicks', 'https://newspicks.com/', '株式会社ユーザベース ');
INSERT INTO websites (id, name, url, company_name) VALUES (35, 'ウォール・ストリート・ジャーナル', 'https://jp.wsj.com/', 'Dow Jones&Company（ダウ・ジョーンズ&カンパニー）');
INSERT INTO websites (id, name, url, company_name) VALUES (36, 'ダイヤモンド・オンライン', 'https://diamond.jp/', '株式会社ダイヤモンド社');
INSERT INTO websites (id, name, url, company_name) VALUES (37, 'Forbes JAPAN', 'https://forbesjapan.com/', 'リンクタイズ株式会社');
INSERT INTO websites (id, name, url, company_name) VALUES (38, '東洋経済オンライン', 'https://toyokeizai.net/', '株式会社東洋経済新報社');
INSERT INTO websites (id, name, url, company_name) VALUES (39, 'EL BORDE', 'https://www.nomura.co.jp/el_borde/list.html', '野村證券株式会社');
INSERT INTO websites (id, name, url, company_name) VALUES (40, 'AMP', 'https://amp.review/', '株式会社電通パブリックリレーションズ');
INSERT INTO websites (id, name, url, company_name) VALUES (41, 'XD [クロスディー]', 'https://exp-d.com/', '株式会社プレイド');
INSERT INTO websites (id, name, url, company_name) VALUES (42, 'ログミー', 'https://logmi.jp/', 'ログミー株式会社');
INSERT INTO websites (id, name, url, company_name) VALUES (43, 'WorkMaster', 'https://www.work-master.net/', '株式会社マッシュメディア');
INSERT INTO websites (id, name, url, company_name) VALUES (44, '経営プロ', 'http://keiei.proweb.jp/', 'ProFuture株式会社');
INSERT INTO websites (id, name, url, company_name) VALUES (45, 'BUSINESS LAWYERS', 'https://business.bengo4.com/', '弁護士ドットコム株式会社');
INSERT INTO websites (id, name, url, company_name) VALUES (46, 'Mugendai(無限大)', 'https://www.mugendai-web.jp/', '株式会社メディアジーン');
INSERT INTO websites (id, name, url, company_name) VALUES (47, 'TechCrunch Japan', 'https://jp.techcrunch.com/', 'Verizon Media Japan株式会社 ');
INSERT INTO websites (id, name, url, company_name) VALUES (48, 'ZDNet Japan', 'https://japan.zdnet.com/', '朝日インタラクティブ株式会社');
INSERT INTO websites (id, name, url, company_name) VALUES (49, 'WIRED', 'https://wired.jp/', '合同会社コンデナスト・ジャパン');
INSERT INTO websites (id, name, url, company_name) VALUES (50, 'ビジネス＋IT', 'https://www.sbbit.jp/', 'SBクリエイティブ株式会社');
INSERT INTO websites (id, name, url, company_name) VALUES (51, 'ITmedia NEWS', 'http://www.itmedia.co.jp/news/', 'アイティメディア株式会社');
INSERT INTO websites (id, name, url, company_name) VALUES (52, '@IT', 'http://www.atmarkit.co.jp/', 'アイティメディア株式会社');
INSERT INTO websites (id, name, url, company_name) VALUES (53, 'GIZMODO JAPAN', 'https://www.gizmodo.jp/', '株式会社メディアジーン');
INSERT INTO websites (id, name, url, company_name) VALUES (54, 'CNET Japan', 'https://japan.cnet.com/', '朝日インタラクティブ株式会社');
INSERT INTO websites (id, name, url, company_name) VALUES (55, 'Techable', 'https://techable.jp/', '株式会社PR TIMES');
INSERT INTO websites (id, name, url, company_name) VALUES (56, 'DIGITALIST', 'https://project.nikkeibp.co.jp/digitalist/', 'Sansan株式会社');
INSERT INTO websites (id, name, url, company_name) VALUES (57, 'freshtrax', 'http://blog.btrax.com/jp/', 'ビートラックスジャパン合同会社');
INSERT INTO websites (id, name, url, company_name) VALUES (58, 'TechWave', 'http://techwave.jp/', '株式会社テックウェーブ');
INSERT INTO websites (id, name, url, company_name) VALUES (59, 'GIGAZINE', 'http://gigazine.net/', '株式会社OSA');
INSERT INTO websites (id, name, url, company_name) VALUES (60, 'サイボウズ式', 'https://cybozushiki.cybozu.co.jp/', 'サイボウズ株式会社');
INSERT INTO websites (id, name, url, company_name) VALUES (61, '日経 xTECH', 'https://tech.nikkeibp.co.jp/', '株式会社日経BP');
INSERT INTO websites (id, name, url, company_name) VALUES (62, 'データのじかん', 'https://data.wingarc.com/', 'ウイングアーク１ｓｔ株式会社');
INSERT INTO websites (id, name, url, company_name) VALUES (63, 'LoveTechMedia', 'https://lovetech-media.com/', 'あいテクテク株式会社');
INSERT INTO websites (id, name, url, company_name) VALUES (64, '「分かりそう」で「分からない」でも「分かった」気になれるIT用語辞典', 'https://wa3.i-3-i.info/index.html', 'Piyopiyo Create Service');
INSERT INTO websites (id, name, url, company_name) VALUES (65, 'FROGGY', 'https://www.froggy.money/', 'ＳＭＢＣ日興証券株式会社');
INSERT INTO websites (id, name, url, company_name) VALUES (66, 'DAILY ANDS', 'https://daily-ands.jp/', '株式会社ZUU');
INSERT INTO websites (id, name, url, company_name) VALUES (67, 'MONEY PLUS', 'https://moneyforward.com/media/', '株式会社マネーフォワード');
INSERT INTO websites (id, name, url, company_name) VALUES (68, 'Mocha', 'https://fpcafe.jp/mocha', '株式会社Money＆You');
INSERT INTO websites (id, name, url, company_name) VALUES (69, 'MarkeZine', 'https://markezine.jp/', '株式会社翔泳社');
INSERT INTO websites (id, name, url, company_name) VALUES (70, 'Agenda note', 'https://agenda-note.com/', '株式会社ナノベーション');
INSERT INTO websites (id, name, url, company_name) VALUES (71, 'アプリマーケティング研究所', 'https://appmarketinglabo.net/', 'アプリマーケティング研究所');
INSERT INTO websites (id, name, url, company_name) VALUES (72, 'marketeer', 'https://marketeer.jp/', 'アナグラム株式会社');
INSERT INTO websites (id, name, url, company_name) VALUES (73, 'SAIRU NOTE', 'https://sairu.co.jp/doernote/', '株式会社才流');

-- +goose Down
-- SQL section 'Down' is executed when this migration is rolled back
DELETE from websites WHERE id BETWEEN 1 AND 73;
SELECT setval('websites_id_seq', 1, false);
