version: '3' # composeファイルのバーション指定
services:
  backend:
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env.dev

  frontend:
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    env_file:
      - .env.dev
    environment:
      - MODE=development

  frontend-user:
    ports:
      - ${FRONTEND_USER_PORT}:${FRONTEND_USER_PORT}
    env_file:
      - .env.local
    environment:
      - MODE=development

  postgres:
    ports:
      - ${PSQL_HOST_PORT}:${PSQL_PORT}
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASS}
      POSTGRES_DB: ${PSQL_DBNAME}

  redis:
    ports:
      - ${REDIS_HOST_PORT}:${REDIS_PORT}
    env_file:
      - .env.dev
