version: '3' # composeファイルのバーション指定
services:
  backend:
    build: ./backend # ビルドに使用するDockerfileがあるディレクトリ指定
    tty: true # コンテナの起動永続化。Bashが入力待ち状態になるよう指定（nginxやmysqlのようにポートを開いて待受けするシステムの場合は指定不要）
    volumes:
      - type: bind
        source: "."
        target: "/go/src/tiger_app/" # マウントディレクトリ指定
    environment:
      - "GOPATH=/go/"
    depends_on:
      - postgres
      - redis

  frontend:
    build: ./frontend
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: "."
        target: "/go/src/tiger_app/" # マウントディレクトリ(全体)指定
    depends_on:
      - postgres
      - redis
      - backend

  postgres:
    build: ./postgres
    volumes: # マウントの設定 ... ホスト側ディレクトリ:コンテナ側ディレクトリ
      - ./db/sh:/docker-entrypoint-initdb.d # この中の.sh、.sqlファイルは自動実行される
      - ./db/data:/data # db.dumpを配置する
      - ./db/storage:/var/lib/postgresql/data # データベースデータを永続化する

  redis:
    build: ./redis
    volumes:
      - type: bind
        source: "./redis/data"
        target: "/go/src/tiger_app/redis/data" # マウントディレクトリ(全体)指定"
