version: 2.1
jobs:
  backend:
    working_directory: ~/tiger_app/backend
    docker: # ジョブを実行するマシンを定義
      - image: cimg/go:1.17
    steps:
      - checkout
      - run: go env -w GO111MODULE=on
      - run: go env
      - restore_cache:
          key: mod-{{ checksum "go.sum" }}
      - run: go mod init backend
      - run: go mod tidy
      - run:
          name: Run golang tests
          command: go test -v
workflows:
  test_workflow: # workflowの名前
    jobs:
      - backend # 実行するjobの順番
