version: 2.1
jobs:
  backend:
    working_directory: ~/tiger_app/backend
    docker: # ジョブを実行するマシンを定義
      - image: cimg/go:1.17
    steps:
      - checkout
      - run: go env -w GO111MODULE=on
      - run: go env
      - go/load-cache
      - go/mod-download
      # - run: go mod init github.com/unemekenta/tiger_app
      # - run: go mod download
      - run:
          name: Run golang tests
          command: go test testing
      - go/save-cache
workflows:
  test_workflow: # workflowの名前
    jobs:
      - backend # 実行するjobの順番
