version: 2.1
jobs:
  backend:
    working_directory: ~/tiger_app/backend
    docker: # ジョブを実行するマシンを定義
      - image: cimg/go:1.17
    steps:
      - run: go env
      - checkout # コードをレポジトリからチェックアウト
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "~/tiger_app/backend/go.sum" }}
            - go-module-cache-v1-
      - run:
          name: Vendoring
          command: go mod init
      - save_cache:
          key: go-mod-v4-{{ checksum "~/tiger_app/backend/go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run golang tests
          command: go test -v
workflows:
  test_workflow: # workflowの名前
    jobs:
      - backend # 実行するjobの順番
